### ISSUE TITLE
Game Options not enabled in new saves

### ISSUE THREAD

**Issue by Leonx254** [JackoboLeChocobo/Sonic-1-2-2013-Decompilation#2]
-Os: Windows 10 64 bits

-Bug: Options are not taken into consideration when you create a new save, they work if you exit the save and re-enter, and they work on No Save mode

**Comment by JackoboLeChocobo** [comment]
Issue confirmed : it is indeed when we create a new save slot game. Exit and reload the save slot loads the goods options.
Thanks for this report : I will check that

**Comment by JackoboLeChocobo** [comment]
Issue fixed, added security saveRAM and options.XXXX values
