### ISSUE TITLE
Menu GUI's have black borders in default ScreenWidth

### ISSUE THREAD

**Issue by Leonx254** [JackoboLeChocobo/Sonic-1-2-2013-Decompilation#3]
OS: Windows 10 64 bits
Bug: using the default 424 of ScreenWidth causes the menus to have a small black border on the sides
![image](https://user-images.githubusercontent.com/59059689/109423618-f10f7000-79be-11eb-90e2-90f8a3f58669.png)
![image](https://user-images.githubusercontent.com/59059689/109423640-10a69880-79bf-11eb-9016-a6f7dc6fb0da.png)
![image](https://user-images.githubusercontent.com/59059689/109423670-3c298300-79bf-11eb-8fc4-884087aea2fd.png)

**Comment by JackoboLeChocobo** [comment]
It's because the size of the layouts are 420x240 . The 16:9 size is 424 on width ? ^^"

**Comment by JackoboLeChocobo** [comment]
Issue fixed : backgrounds for Title Screen and Main Mena have a size of 1024x240. The Options Menu has the good background color now. Will be on 1.0.1

**Comment by JackoboLeChocobo** [comment]
Test Screen : 500x240
![image](https://user-images.githubusercontent.com/42393934/109425719-fafa9880-79e9-11eb-9af7-2fc979e7afea.png)
